version: '3'

services:
    database:
        container_name: database
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: campfire
            MYSQL_ROOT_PASSWORD: distribuidas
        expose:
            - "3306"

    langfilter:
        container_name: langfilter
        build: ./langfilter
        expose:
            - "9092"

    langfilter2:
        container_name: langfilter2
        build: ./langfilter
        expose:
            - "9092"
  
    campfire:
        container_name: campfire
        build: ./campfire
        expose:
            - "8443"
            - "5701"
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/campfire    
        depends_on:
            - database
            - langfilter
        restart: on-failure

    campfire2:
        container_name: campfire2
        build: ./campfire
        expose:
            - "8443"
            - "5701"
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/campfire    
        depends_on:
            - database
            - langfilter
        restart: on-failure
    
    loadbalancer:
        container_name: loadbalancer
        build: ./haproxy
        ports:
            - "80:80"
            - "443:443"
        environment:
            LOG_LEVEL: "debug"
        depends_on:
            - campfire

    internal_loadbalancer:
        container_name: internal_loadbalancer
        build: ./internal_haproxy
        ports:
            - "8080:8080"
            - "9080:9080"
        environment:
            LOG_LEVEL: "debug"
        depends_on:
            - langfilter
    


    