version: '3'

services:
    database:
        container_name: database
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: campfire
            MYSQL_ROOT_PASSWORD: distribuidas
        ports:
            - "3306:3306"

    langfilter:
        container_name: langfilter
        build: ./langfilter
        ports:
            - "9092:9092"
  
    campfire:
        container_name: campfire
        build: ./campfire
        ports:
            - "8443:8443"
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/campfire    
        depends_on:
            - database
            - langfilter
        restart: on-failure

    loadbalancer:
        container_name: loadbalancer
        build: ./haproxy
        ports:
            - "80:80"
            - "443:443"
        environment:
            LOG_LEVEL: "debug"
        depends_on:
            - campfire

    