version: '3'

services:

    mysql_master:
        image: mysql:5.7
        env_file:
            - ./mysql/master/mysql_master.env
        container_name: "mysql_master"
        restart: "no"
        expose:
            - "3306"
        volumes:
            - ./mysql/master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
            - ./mysql/master/data:/var/lib/mysql

    mysql_slave:
        image: mysql:5.7
        env_file:
            - ./mysql/slave/mysql_slave.env
        container_name: "mysql_slave"
        restart: "no"
        expose:
            - "3306"
        depends_on:
            - mysql_master
        volumes:
            - ./mysql/slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
            - ./mysql/slave/data:/var/lib/mysql

    langfilter-a:
        container_name: langfilter-a
        build: ./langfilter
        expose:
            - "9092"

    langfilter-b:
        container_name: langfilter-b
        build: ./langfilter
        expose:
            - "9092"
  
    campfire-a:
        container_name: campfire-a
        build: ./campfire
        expose:
            - "8443"
            - "5701"
        depends_on:
            - mysql_master
            - langfilter-a
            - langfilter-b
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql:replication://mysql_master:3306,mysql_slave:3306/campfire
            #- SPRING_DATASOURCE_URL=jdbc:mysql://mysql_master:3306/campfire
        restart: on-failure

    campfire-b:
        container_name: campfire-b
        build: ./campfire
        expose:
            - "8443"
            - "5701"  
        depends_on:
            - mysql_master
            - langfilter-a
            - langfilter-b
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql:replication://mysql_master:3306,mysql_slave:3306/campfire
            #- SPRING_DATASOURCE_URL=jdbc:mysql://mysql_master:3306/campfire
        restart: on-failure

    campfire-c:
        container_name: campfire-c
        build: ./campfire
        expose:
            - "8443"
            - "5701"  
        depends_on:
            - mysql_master
            - langfilter-a
            - langfilter-b
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql:replication://mysql_master:3306,mysql_slave:3306/campfire
        restart: on-failure
    
    campfire_loadbalancer:
        container_name: campfire_loadbalancer
        build: ./haproxy
        ports:
            - "80:80"
            - "443:443"
        environment:
            LOG_LEVEL: "debug"
        depends_on:
            - campfire

    internal_loadbalancer:
        container_name: internal_loadbalancer
        build: ./internal_haproxy
   #     ports:
   #         - "8080:8080"
   #         - "9080:9080"
        expose:
            - "8080"
            - "9080"
        environment:
            LOG_LEVEL: "debug"
        depends_on:
            - langfilter
    


    