services:
    database:
        container_name: database
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: campfire
            MYSQL_ROOT_PASSWORD: distribuidas
        expose:
            - "3306"
        
    campfire:
        container_name: campfire
        build: ./campfire
        ports:
            - "8443:8443"
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/campfire    
        links:
            - database
            - langfilter
        restart: on-failure

    langfilter:
        container_name: langfilter
        build: ./langfilter
        expose:
            - "9092"